version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # Used to sync our local code changes to the docker container
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    # - ./.env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      # TODO: Add database username
      - DATABASE_USERNAME=
      # TODO: Add database password
      - DATABASE_PASSWORD=
      - DATABASE_NAME=fastapi
      # TODO: Add secret key for auth
      - SECRET_KEY=
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      # TODO: Add database password
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: